/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package project_euler.level01;

import java.math.BigInteger;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import project_euler.util.MD5Hash;

/**
 *
 * @author Joonas Asikainen <tjasikai@mac.com>
 */
public class Problem029 {

    /**
     *
     * @param args
     */
    public static void main(String[] args) {
        try {
            final HashMap<String, Integer> checker = new HashMap<String, Integer>();
            final MD5Hash md5 = new MD5Hash();
            for (int a = 2; a <= 100; a++) {
                final String strA = String.valueOf(a);
                final BigInteger ba = new BigInteger(strA);
                for (int b = 2; b <= 100; b++) {
                    final BigInteger result = ba.pow(b);
                    String hash = md5.getHexStringHash(result.toString());
                    checker.put(hash, checker.size());
                }
            }
            System.out.println("# distinct = " + checker.size());
        } catch (Exception ex) {
            Logger.getLogger(Problem029.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
//
// Consider all integer combinations of ab for 2  a  5 and 2  b  5:
//
// 22=4, 23=8, 24=16, 25=32
// 32=9, 33=27, 34=81, 35=243
// 42=16, 43=64, 44=256, 45=1024
// 52=25, 53=125, 54=625, 55=3125
// If they are then placed in numerical order, with any repeats removed,
// we get the following sequence of 15 distinct terms:
//
// 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
//
// How many distinct terms are in the sequence generated by ab for 2
// a <= 100 and 2  b <= 100?